default:
    @just --list

build:
    go build ./...

test:
    go test -race -count=1 ./...

test-all: test
    cd provider/anthropic && go test -race -count=1 ./...
    cd provider/openai && go test -race -count=1 ./...
    cd provider/gemini && go test -race -count=1 ./...

vet:
    go vet ./...
    cd provider/anthropic && go vet ./...
    cd provider/openai && go vet ./...
    cd provider/gemini && go vet ./...

clean:
    go clean -testcache
